const movies = [
  "avatar",
  "the matrix",
  "titanic",
  "inception",
  "jaws",
  "jurassic park",
  "star wars",
  "forrest gump",
  "the shawshank redemption",
  "fight club",
  "braveheart",
  "pulp fiction",
  "the matrix reloaded",
  "goodfellas",
  "the silence of the lambs",
  "gladiator",
  "casablanca",
  "the shining",
  "rocky",
  "aliens",
  "terminator",
  "e.t. the extra-terrestrial",
  "reservoir dogs",
  "blade runner",
  "the godfather",
  "saving private ryan",
  "shawshank redemption",
  "forrest gump",
  "the lion king",
  "the great gatsby",
  "apocalypse now",
  "schindler's list",
  "american psycho",
  "the martian",
  "black swan",
  "whiplash",
  "interstellar",
  "the prestige",
  "dead poets society",
  "the green mile",
  "pan's labyrinth",
  "inception",
  "catch me if you can",
  "gladiator",
  "moulin rouge!",
  "independence day",
  "the incredibles",
  "transformers"
];

// Export the movies array for use in other JavaScript files
export default movies;
