const musicWords = [
  "Bohemian Rhapsody",
  "Imagine",
  "Hotel California",
  "Yesterday",
  "Smells Like Teen Spirit",
  "Like a Rolling Stone",
  "Billie Jean",
  "Johnny B. Goode",
  "Hey Jude",
  "Sweet Child o’ Mine",
  "Purple Haze",
  "What’s Going On",
  "Imagine",
  "What’s Love Got to Do with It",
  "Let It Be",
  "I Want to Hold Your Hand",
  "Every Breath You Take",
  "Rolling in the Deep",
  "Wonderwall",
  "Stairway to Heaven",
  "Boys Don’t Cry",
  "Livin’ on a Prayer",
  "Imagine",
  "Superstition",
  "Let’s Get It On",
  "My Generation",
  "Blowin’ in the Wind",
  "Another Brick in the Wall",
  "I Want to Dance with Somebody",
  "Purple Rain",
  "Sweet Caroline",
  "Eye of the Tiger",
  "Like a Prayer",
  "American Pie",
  "A Day in the Life",
  "Smells Like Teen Spirit",
  "Don’t Stop Believin’",
  "Imagine",
  "Yesterday",
  "Imagine",
  "Hotel California",
  "Billie Jean",
  "What’s Going On",
  "Bohemian Rhapsody",
  "Like a Rolling Stone",
  "Hey Jude",
  "Imagine",
  "Sweet Child o’ Mine",
  "What’s Love Got to Do with It",
  "Johnny B. Goode",
  "Yesterday",
  "Purple Haze",
  "Let It Be",
  "Every Breath You Take",
  "Rolling in the Deep",
  "Wonderwall",
  "Stairway to Heaven",
  "Boys Don’t Cry",
  "Livin’ on a Prayer",
  "What’s Going On",
  "Superstition",
  "Let’s Get It On",
  "My Generation",
  "Blowin’ in the Wind",
  "Another Brick in the Wall",
  "I Want to Dance with Somebody",
  "Purple Rain",
  "Sweet Caroline",
  "Eye of the Tiger",
  "Like a Prayer",
  "American Pie",
  "A Day in the Life",
  "Smells Like Teen Spirit",
  "Don’t Stop Believin’",
  "Yesterday",
  "Imagine",
  "Hotel California",
  "Billie Jean",
  "What’s Going On",
  "Bohemian Rhapsody",
  "Like a Rolling Stone",
  "Hey Jude",
  "Imagine",
  "Sweet Child o’ Mine",
  "Johnny B. Goode",
  "What’s Love Got to Do with It",
  "Purple Haze",
  "Let It Be",
  "Every Breath You Take",
  "Rolling in the Deep",
  "Wonderwall",
  "Stairway to Heaven",
  "Boys Don’t Cry",
  "Livin’ on a Prayer",
  "Imagine",
  "Superstition",
  "Let’s Get It On",
  "My Generation",
  "Blowin’ in the Wind",
  "Another Brick in the Wall",
  "I Want to Dance with Somebody",
  "Purple Rain",
  "Sweet Caroline",
  "Eye of the Tiger",
  "Like a Prayer",
  "American Pie",
  "A Day in the Life",
  "Smells Like Teen Spirit",
  "Don’t Stop Believin’",
  "Imagine",
  "Yesterday",
  "Imagine",
  "Hotel California",
  "Billie Jean",
  "What’s Going On",
  "Bohemian Rhapsody",
  "Like a Rolling Stone",
  "Hey Jude",
  "Imagine",
  "Sweet Child o’ Mine",
  "What’s Love Got to Do with It",
  "Johnny B. Goode",
  "Yesterday",
  "Purple Haze",
  "Let It Be",
  "Every Breath You Take",
  "Rolling in the Deep",
  "Wonderwall",
  "Stairway to Heaven",
  "Boys Don’t Cry",
  "Livin’ on a Prayer",
  "What’s Going On",
  "Superstition",
  "Let’s Get It On",
  "My Generation",
  "Blowin’ in the Wind",
  "Another Brick in the Wall",
  "I Want to Dance with Somebody",
  "Purple Rain",
  "Sweet Caroline",
  "Eye of the Tiger",
  "Like a Prayer",
  "American Pie",
  "A Day in the Life",
  "Smells Like Teen Spirit",
  "Don’t Stop Believin’"
];

// Export the music words array for use in other JavaScript files
export default musicWords;
