const sportsWords = [
  "soccer",
  "basketball",
  "football",
  "tennis",
  "baseball",
  "golf",
  "swimming",
  "volleyball",
  "hockey",
  "cricket",
  "badminton",
  "table tennis",
  "rugby",
  "cycling",
  "running",
  "boxing",
  "wrestling",
  "gymnastics",
  "skiing",
  "snowboarding",
  "surfing",
  "skateboarding",
  "karate",
  "taekwondo",
  "judo",
  "archery",
  "fencing",
  "shooting",
  "climbing",
  "rowing",
  "sailing",
  "horseback riding",
  "triathlon",
  "marathon",
  "sprint",
  "long jump",
  "high jump",
  "shot put",
  "swimming relay",
  "water polo",
  "formula 1",
  "motocross",
  "boxing ring",
  "tennis court",
  "golf course",
  "ski slope",
  "snowboard park"
];

// Export the sports words array for use in other JavaScript files
export default sportsWords;
