const technologyWords = [
  "computer",
  "smartphone",
  "tablet",
  "laptop",
  "robot",
  "drone",
  "artificial intelligence",
  "machine learning",
  "virtual reality",
  "augmented reality",
  "blockchain",
  "cybersecurity",
  "data science",
  "cloud computing",
  "web development",
  "programming",
  "software",
  "hardware",
  "networking",
  "internet of things",
  "5G",
  "biotechnology",
  "nanotechnology",
  "space exploration",
  "3D printing",
  "autonomous vehicles",
  "digital marketing",
  "smart home",
  "wearable technology",
  "fintech",
  "e-commerce",
  "gaming",
  "telecommunications",
  "satellite technology",
  "bioinformatics",
  "genetic engineering",
  "quantum computing",
  "green technology",
  "solar panels",
  "wind turbines",
  "electric vehicles",
  "biofuels",
  "drones",
  "supercomputing",
  "nanomedicine",
  "bionics",
  "data analytics",
  "computer vision"
];

// Export the technology words array for use in other JavaScript files
export default technologyWords;
